server:
  port: 9086

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.173.108.167:1111/maratonproduct
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#myapplication:
#  stock-service:
#    feign-client: http://localhost:9088/api/v1/stock
#
